export const DRIVER_RESPONDED = 'DRIVER_RESPONDED';
export const MATCHED_DRIVER_STATE = 'MATCHED_DRIVER_STATE';
export const MATCHED_RIDER_STATE = 'MATCHED_RIDER_STATE';
export const CALL_REQUESTED = 'CALL_REQUESTED';
